name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - { uses: actions/checkout@v4 }
    - { name: Set up JDK, uses: actions/setup-java@v4, with: { distribution: "temurin", java-version: "21" } }
    - { name: Prepare Gradle, uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 } # https://github.com/gradle/actions/releases/tag/v3.5.0
    - name: Build with Gradle
      #run: ./gradlew -s -i check
      run: ./gradlew -s -i jvmTest
    - name: Check version
      run: ./ktcc_jvm -version
    - name: Integration tests
      run: |
        wget https://github.com/holgerbrandl/kscript/releases/download/v2.8.0/kscript-2.8.0-bin.zip
        unzip kscript-2.8.0-bin.zip
        export PATH=$PATH:./kscript-2.8.0/bin/
        ./ktcc_jvm_integration_test
