name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      #run: ./gradlew -s -i check
      run: ./gradlew -s -i jvmTest
    - name: Check version
      run: ./ktcc_jvm -version
    - name: Integration tests
      run: |
        wget https://github.com/holgerbrandl/kscript/releases/download/v2.8.0/kscript-2.8.0-bin.zip
        unzip kscript-2.8.0-bin.zip
        export PATH=$PATH:./kscript-2.8.0/bin/
        ./ktcc_jvm_integration_test
